# Generated by Django 6.0.6 on 2026-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transactions_status_transactions_void_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Kode Produk'),
        ),
    ]
