# Generated by Django 6.0.6 on 2026-06-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stockadjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='subtotal_amount',
            field=models.IntegerField(default=0),
        ),
    ]
